name: Release

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.5.2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
  release-branch:
    name: Publish branch
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}
    environment: Production
    steps:
      - name: Init
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.5.2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Publish to npm and GitHub
        run: |
          git config --global user.email "balazsorban44@users.noreply.github.com"
          git config --global user.name "Balázs Orbán"
          pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
