name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release-branch:
    name: Publish branch
    runs-on: ubuntu-latest
    # needs: test
    if: ${{ github.event_name == 'push' }}
    environment: Production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Please upvote https://github.com/orgs/community/discussions/13836
          token: ${{ secrets.GH_PAT }}
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Please upvote https://github.com/orgs/community/discussions/13836
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
